Repository summa-tx/coins, pull requests merged in 2020-08, with the labels that each got.

#62 Fix compile errors
  bip32/src/prelude.rs
  ledger-btc/src/app.rs
Labels: bug

#68 chores: #53 - macros to core. fix bip32 bench. fix wasm-pack
  bip32/benches/bench.rs
  bip32/src/derived.rs
  bip32/src/prelude.rs
  bitcoins-wasm/Cargo.toml
  bitcoins/src/builder.rs
  bitcoins/src/enc/encoder.rs
  bitcoins/src/hashes.rs
  bitcoins/src/lib.rs
  bitcoins/src/types/legacy.rs
  bitcoins/src/types/script.rs
  bitcoins/src/types/witness.rs
  core/src/lib.rs
  core/src/macros.rs
  core/src/ser.rs
  ledger-btc/Cargo.toml
  ledger-btc/tests/integration.rs
  ledger/Cargo.toml
  ledger/node_tests/package-lock.json
  ledger/node_tests/package.json
  litecoins/Cargo.toml
  provider/Cargo.toml
  provider/src/utils.rs
  psbt/Cargo.toml
  psbt/src/common.rs
  psbt/src/lib.rs
  psbt/src/roles/bip32_signer.rs
Labels: bug, core

#43 Handshake Support
  Cargo.toml
  core/Cargo.toml
  core/src/enc/bases.rs
  core/src/hashes/blake2b256.rs
  core/src/hashes/mod.rs
  core/src/hashes/sha3_256.rs
  handshakes/Cargo.toml
  handshakes/README.md
  handshakes/src/builder.rs
  handshakes/src/defaults.rs
  handshakes/src/enc/bases.rs
  handshakes/src/enc/encoder.rs
  handshakes/src/enc/mod.rs
  handshakes/src/hashes.rs
  handshakes/src/lib.rs
  handshakes/src/nets.rs
  handshakes/src/prelude.rs
  handshakes/src/types/covenant.rs
  handshakes/src/types/lockingscript.rs
  handshakes/src/types/mod.rs
  handshakes/src/types/script.rs
  handshakes/src/types/tx.rs
  handshakes/src/types/txin.rs
  handshakes/src/types/txout.rs
Labels: enhancement
